### ISSUE TITLE
Ip still mine even after seeting ep everything right 

### ISSUE THREAD

**Issue by N30Z3N** [x0rzavi/ephemeral-vpn#1]
I followed all the steps as you shown my dashboard shows 
![image](https://user-images.githubusercontent.com/54675598/180283558-9b566a55-cf1f-4a85-91e5-f5f4a2b86d4d.png)
I'm using tailscale on kali linux and my ip is default everywhere

`100.xx.xx.xx   kali                 bnsave100@   linux   -`
`100.xx.xx.xx   ephermeral-vpn-9693  tagged-devices linux   idle; offers exit node`

**Comment by x0rzavi** [comment]
Make sure you are actually using the exit node https://tailscale.com/kb/1103/exit-nodes/#step-3-use-the-exit-node

**Comment by N30Z3N** [comment]
> Make sure you are actually using the exit node https://tailscale.com/kb/1103/exit-nodes/#step-3-use-the-exit-node

thanks a lot for helping out :)
