### ISSUE TITLE
How can I connect two tailscale running machines in a relay 

### ISSUE THREAD

**Issue by N30Z3N** [x0rzavi/ephemeral-vpn#2]
I have two machines running rn one my seedbox and heroku now I want to use both routing my connection interchangeably 
e.g. me --------> heroku machine --------> seedbox (exit node) and likely combinations Is there any way to do so ?

**Comment by x0rzavi** [comment]
Please consult [tailscale docs](https://tailscale.com/kb/). If you find your preferred workflow and its something which I can improve upon in this repo, reply back
